import type { APIRoute } from "astro";

/**
 * Canonical /sitemap.xml entry point.
 *
 * @astrojs/sitemap generates `sitemap-index.xml` and `sitemap-0.xml`. Most
 * crawlers and SEO tools try `/sitemap.xml` by convention, so this endpoint
 * mirrors the index so that conventional path resolves too. The actual URL
 * list lives in `sitemap-0.xml` and is regenerated by the integration on
 * every build — this file does not need to be updated when pages are added.
 */
export const GET: APIRoute = ({ site }) => {
  if (!site) {
    return new Response("astro.config.mjs site is not set", { status: 500 });
  }

  const body = `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <sitemap>
    <loc>${new URL("sitemap-0.xml", site).toString()}</loc>
  </sitemap>
</sitemapindex>
`;

  return new Response(body, {
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
    },
  });
};
